### ISSUE TITLE
Googłe Play Games installation not found

### ISSUE THREAD

**Issue by vysmaty** [CanRanBan/PlayniteExtension-Library-GooglePlayGames#1]
Hi, unfortunately I'm still getting the error:
27-12 23:48:17.649|ERROR|GooglePlayGamesLibrary#GooglePlayGamesLibrary:Google Play Games installation not found.

And I don't know how to debug it. I verified that there are keys in the registry:
Počítač\HKEY_LOCAL_MACHINE\SOFTWARE\Google\Play Games

And the files
"C:\Program Files\Google\Play Games\Bootstrapper.exe"
"C:\Program Files\Google\Play Games\current\service\Service.exe"

Thank You.

**Comment by CanRanBan** [comment]
Google changed their installer after my first installation and broke the updater for earlier installations.
Should be resolved with [v0.1.2](https://github.com/CanRanBan/PlayniteExtension-Library-GooglePlayGames/releases/tag/v0.1.2).
